# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x.x
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 22.15.x
    - name: Restore dependencies
      run: cd src/VKProxy.Admin/VKProxy.Admin.Server && dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: build ui
      run: cd src/VKProxy.Admin/vkproxy.admin.client && npm i npm-run-all --save-dev && npm install && npm run build
    - name: CP ui 
      run: cd src/VKProxy.Admin && cp -r vkproxy.admin.client/dist VKProxy.Admin.Server/bin/Release/net9.0/wwwroot && ls VKProxy.Admin.Server/bin/Release/net9.0/wwwroot
    - name: Docker Setup Docker
      uses: docker/setup-docker-action@v4.3.0
    - name: build img
      run: cd src/VKProxy.Admin && docker build -t vkproxy/ui:0.0.0.1 .
          
