# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x.x
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.4.0
      with:
        node-version: 16.17.0
    - name: Restore dependencies
      run: cd src/VKProxy.Admin/VKProxy.Admin.Server && dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: build ui
      run: cd src/VKProxy.Admin/vkproxy.admin.client && npm run build
    - name: CP ui 
      run: cp -r src/VKProxy.Admin/vkproxy.admin.client/dist src/VKProxy.Admin/VKProxy.Admin.Server/bin/Release/net9.0/wwwroot

